security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # The main authentication firewall
            form_login:
                login_path: login
                check_path: login
            logout:
                path: app_logout
                # Define the redirect after logout
                target: /

            # Enable remember me if needed
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 31536000 # 1 year
                path: /

    access_control:
        # Access control based on roles
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
