framework:
    asset_mapper:
        # Les chemins vers les fichiers à mapper
        paths:
            - assets/
            - vendor/symfony/stimulus-bundle/assets/dist/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
