doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            json: Symfony\Component\Doctrine\DBAL\Types\JsonType;

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
