framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    form: true
    http_method_override: true
    session:
        handler_id: null
        cookie_secure: auto
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
    router:
        utf8: true

    # Active les tests
    test: true
