security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Le firewall principal
            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout  # Utilisation de la route /logout pour la déconnexion
                target: /      # Redirection vers la page d'accueil après déconnexion

            # Activer "remember me" si nécessaire
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 31536000 # 1 an
                path: /

    access_control:
        # Contrôle d'accès en fonction des rôles
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
