security:
    password_hashers:
      App\Entity\User:
        algorithm: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/manager, roles: ROLE_MANAGER }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }
        - { path: ^/login, roles: PUBLIC_ACCES }
