# config/routes.yaml

employee_dashboard:
    path: /employee/dashboard
    controller: App\Controller\EmployeeController::dashboard
    requirements:
        _role: ROLE_EMPLOYE

manager_dashboard:
    path: /manager/dashboard
    controller: App\Controller\ManagerController::dashboard
    requirements:
        _role: ROLE_MANAGER

conge_new:
    path: /conge/new
    controller: App\Controller\CongeController::new
