services:
    _defaults:
        autowire: true       # Automatically injects dependencies
        autoconfigure: true  # Automatically registers your services as commands, event listeners, etc.

    # Custom services
    # Example:
    # App\Service\MyCustomService: ~
