services:
    _defaults:
        autowire: true      # Active l'autowiring des services
        autoconfigure: true # Active l'autoconfiguration des services
        public: false       # Les services sont privés par défaut

    # Controllers are automatically registered as services
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Repository,Migration}'
