<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxRHPZR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxRHPZR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxRHPZR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxRHPZR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxRHPZR\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxRHPZR',
    'container.build_id' => '33657185',
    'container.build_time' => 1745338742,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxRHPZR');
